import React from 'react';
import type { GetServerSideProps } from 'next';
import Head from 'next/head';

import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import { requests } from '../utils/requests';
import Movie from '../models/movie';
import axios from 'axios';

interface Props {
  results: Movie[];
}

const Home = ({ results }: Props) => {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async context => {
  const genreQuery = context.query.genre;

  const genre = genreQuery as string;

  const { data } = await axios.get(
    `https://api.themoviedb.org/3/${
      requests[genre]?.url || requests.trending.url
    }`
  );

  return {
    props: { results: data.results },
  };
};

export default Home;
